trigger:
 branches:
   include:
     - none
   exclude:
     - features/**

pool:
 vmImage: ubuntu-latest


variables:
  - group: ArgoCD-Variable



stages:
- stage: Build
  displayName:
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Npm@1
      displayName: NPM Install
      inputs:
        command: custom
        customCommand: install -D tailwindcss postcss autoprefixer

    - task: Npm@1
      displayName: NPM Build
      inputs:
        command: custom
        customCommand: run build

    - task: Docker@2
      displayName: Docker Login
      inputs:
        command: login
        containerRegistry: $(Docker-SC)

    - task: Docker@2
      displayName: Docker Build
      inputs:
        command: build
        containerRegistry: $(Docker-SC)
        repository: $(IMAGE_REPO)
        Dockerfile: '**/Dockerfile'
        buildContext: '.'
        arguments: '--progress=plain'
        tags: |
          $(IMAGE_TAG)

    - task: Docker@2
      displayName: Docker Push
      inputs:
        command: push
        containerRegistry: $(Docker-SC)
        repository: $(IMAGE_REPO)
        tags: |
          $(IMAGE_TAG)