replicaCount: 2

image:
  repository: docker.io/gunjan37raj/nike-landing-page   # <-- apna username daalo
  tag: "v1"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
